# Pytorch tut

In [3]:
%%capture
!pip install torch==1.8.0

In [4]:
import torch
import numpy as np

In [5]:
a = torch.FloatTensor(3, 2)
a

tensor([[0.0000e+00, 2.5244e-29],
        [4.8184e+07, 1.0845e-19],
        [2.8131e+20, 1.7566e+25]])

In [8]:
# Clear tensor's content.
# This is an inplace operation (vs functional), has underscore appended to method name.
# Functional returns a copy of the tensor & the original is untouched.
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
import torch.nn as nn
# Randomly initialised feedforward layer with 2 inputs & 5 outputs.
l = nn.Linear(2, 5)
v = torch.FloatTensor([1, 2])
l(v)

tensor([ 0.2492, -1.9003,  0.6309, -0.4676,  1.7442], grad_fn=<AddBackward0>)

In [15]:
s = nn.Sequential(
    nn.Linear(2, 5),
    nn.ReLU(),
    nn.Linear(5, 20),
    nn.ReLU(),
    nn.Linear(20, 10),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1)
)

In [22]:
s.load_state_dict(s.state_dict())

<All keys matched successfully>

In [23]:
s(torch.FloatTensor([[1, 2]]))

tensor([[0.1162, 0.1069, 0.0641, 0.0820, 0.0865, 0.0665, 0.1661, 0.0648, 0.1346,
         0.1122]], grad_fn=<SoftmaxBackward>)