# Scratch space

In [12]:
import numpy as np
from collections import deque

In [30]:
num_floors = 3 + 1
num_ppl = 4

In [77]:
floor_num = list(range(num_floors))
# floor_num.reverse()
e = np.array(floor_num).reshape(num_floors, 1)
e

array([[0],
       [1],
       [2],
       [3]])

In [76]:
# e = {str(_):deque(maxlen=num_ppl) for _ in range(num_floors)}
# e["1"].append(5)
# e["1"].maxlen
# e

array([[0],
       [1],
       [2],
       [3]])

In [95]:
b = np.zeros([num_floors, num_ppl])
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b[1] = 1

In [82]:
import random

# round(random.uniform(40, 150), 2)

integer_list = random.sample(range(400, 1500), num_ppl)
float_list = [x/10 for x in integer_list]
float_list

[111.5, 89.1, 57.7, 45.3]

In [83]:
pop = float_list.pop()
pop

45.3

In [84]:
float_list


[111.5, 89.1, 57.7]

In [94]:
rand_floor = random.choice(range(1, num_floors))
rand_floor


1

In [89]:
poop = []
for i in range(num_floors):
    print(i)

0
1
2
3


In [17]:
e

array([3, deque([], maxlen=4)], dtype=object)

In [18]:
b

array([[1.],
       [1.],
       [1.]])